wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD065_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD066_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD067_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD068_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD069_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD070_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD071_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD072_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD073_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD074_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD075_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Manhattan/31MANHATTAN_AD076_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD077_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD078_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD079_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD080_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD081_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD082_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD083_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD084_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD085_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD086_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Bronx/03BRONX_AD087_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD041_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD042_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD043_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD044_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD045_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD046_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD047_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD048_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD049_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD050_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD051_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD052_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD053_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD054_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD055_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD056_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD057_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD058_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD059_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD060_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Brooklyn/24BROOKLYN_AD064_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD023_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD024_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD025_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD026_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD027_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD028_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD029_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD030_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD031_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD032_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD033_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD034_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD035_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD036_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD037_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD038_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD039_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/Queens/41QUEENS_AD040_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/StatenIsland/43STATENISLAND_AD061_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/StatenIsland/43STATENISLAND_AD062_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/StatenIsland/43STATENISLAND_AD063_WORKING%20FAMILIESEnrollment.pdf
wget https://www.vote.nyc.ny.us/downloads/pdf/documents/boe/2019EnrollmentBooks/StatenIsland/43STATENISLAND_AD064_WORKING%20FAMILIESEnrollment.pdf